ALTER TABLE email_inboxes
    ADD COLUMN IF NOT EXISTS smtp_host TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS smtp_port INTEGER NOT NULL DEFAULT 587,
    ADD COLUMN IF NOT EXISTS label TEXT NOT NULL DEFAULT '';
