"use client";

import { type KeyboardEvent } from "react";
import { type ConversationDTO, type MessageDTO, type ToolCallRecord } from "@/lib/api";
import { Spinner } from "@/components/ui/Spinner";
import { FileIcon } from "@/components/ui/icons";

// ─── Extracted chat sub-components ───
import {
  FlagIcon,
  automationLabel,
  useChatSession,
  MessageItem,
  ToolItem,
} from "@/components/chat";

type ChatShellProps = {
  activeConversationId: string | null;
  onActiveConversationChange: (id: string | null) => void;
  onConversationsUpdate: (conversations: ConversationDTO[]) => void;
  readOnly?: boolean;
};

export default function ChatShell({
  activeConversationId,
  onActiveConversationChange,
  onConversationsUpdate,
  readOnly = false,
}: ChatShellProps) {
  const {
    conversations,
    messages,
    toolCallHistory,
    composing,
    setComposing,
    providers,
    selectedProvider,
    setSelectedProvider,
    sending,
    lastUsage,
    streamingMsgId,
    loadingConvs,
    loadingMsgs,
    attachedFiles,
    regeneratingId,
    copiedId,
    recording,
    transcribing,
    messagesEndRef,
    composeRef,
    fileInputRef,
    handleSend,
    handleRegenerate,
    handleCopy,
    handleMic,
    handleFilesPicked,
    removeAttachment,
  } = useChatSession({
    activeConversationId,
    onActiveConversationChange,
    onConversationsUpdate,
  });

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const activeConversation = conversations.find((conv) => conv.id === activeConversationId) ?? null;
  const activeConversationAutomatic = !!activeConversation?.isAutomatic;

  return (
    <div className="flex h-full w-full overflow-hidden">
      {/* ── Center: Message Area ── */}
      <div className="flex-1 flex flex-col min-w-0 h-full relative">
        {activeConversationAutomatic && activeConversation && (
          <div className="shrink-0 px-6 pt-4">
            <div className="mx-auto flex max-w-3xl items-start gap-3 rounded-sm bg-surface-mid px-4 py-3 shadow-[0_12px_32px_rgba(0,0,0,0.10)] backdrop-blur-sm ring-1 ring-[var(--color-outline-ghost)]">
              <div className="mt-0.5 inline-flex h-9 w-9 shrink-0 items-center justify-center rounded-sm bg-violet/12 text-violet">
                <FlagIcon className="h-4 w-4" />
              </div>
              <div className="min-w-0">
                <div className="flex flex-wrap items-center gap-2">
                  <p className="text-sm font-semibold text-on-surface">
                    {automationLabel(activeConversation.automationKind)}
                  </p>
                  <span className="inline-flex items-center rounded-sm bg-violet/12 px-2 py-0.5 text-[10px] font-mono uppercase tracking-[0.18em] text-violet">
                    Auto
                  </span>
                </div>
                <p className="mt-1 text-sm text-on-surface">
                  {activeConversation.title || "Automatic conversation"}
                </p>
                <p className="mt-1 text-xs font-mono text-on-surface-variant">
                  Generated by openCrow automation. Styled separately so automatic runs stand out
                  from manual chats.
                </p>
              </div>
            </div>
          </div>
        )}

        {/* Messages */}
        <div
          className={`flex-1 overflow-y-auto px-6 pb-32 ${activeConversationAutomatic ? "pt-4" : ""}`}
        >
          {!activeConversationId ? (
            <div className="flex items-center justify-center h-full">
              <div className="text-center space-y-2">
                <p className="text-on-surface font-display text-lg">Chat</p>
                <p className="text-on-surface-variant text-sm font-mono">
                  Start a new conversation from the prompt below.
                </p>
                {loadingConvs && (
                  <p className="text-on-surface-variant text-xs">Loading previous chats...</p>
                )}
              </div>
            </div>
          ) : loadingMsgs ? (
            <div className="flex items-center justify-center h-full">
              <Spinner />
            </div>
          ) : messages.length === 0 ? (
            <div className="flex items-center justify-center h-full">
              <p className="text-on-surface-variant text-sm font-mono">
                No messages yet -- start the conversation
              </p>
            </div>
          ) : (
            <div className="flex flex-col gap-3 max-w-3xl mx-auto pt-4">
              {(() => {
                type TimelineItem =
                  | { kind: "message"; item: MessageDTO; idx: number }
                  | { kind: "tool"; item: ToolCallRecord; idx: number };
                const timeline: TimelineItem[] = [
                  ...messages.map((m, idx) => ({ kind: "message" as const, item: m, idx })),
                  ...toolCallHistory.map((t, idx) => ({ kind: "tool" as const, item: t, idx })),
                ].sort((a, b) => {
                  // Live tool calls always appear before the streaming assistant message
                  const aIsStreaming = a.kind === "message" && a.item.id === streamingMsgId;
                  const bIsStreaming = b.kind === "message" && b.item.id === streamingMsgId;
                  const aIsLiveTool = a.kind === "tool" && a.item.id.startsWith("live-");
                  const bIsLiveTool = b.kind === "tool" && b.item.id.startsWith("live-");
                  if (aIsStreaming && bIsLiveTool) return 1;
                  if (bIsStreaming && aIsLiveTool) return -1;

                  const at = new Date(a.item.createdAt).getTime();
                  const bt = new Date(b.item.createdAt).getTime();
                  if (at !== bt) return at - bt;

                  const rank = (entry: TimelineItem) => {
                    if (entry.kind === "tool") return 0;
                    if (entry.item.role === "assistant") return 2;
                    return 1;
                  };
                  const byRank = rank(a) - rank(b);
                  if (byRank !== 0) return byRank;
                  return a.idx - b.idx;
                });

                return timeline.map((entry) => {
                  if (entry.kind === "tool") {
                    return (
                      <ToolItem
                        key={`tool-${entry.item.id}`}
                        tc={entry.item}
                        isLive={entry.item.id.startsWith("live-")}
                      />
                    );
                  }
                  return (
                    <MessageItem
                      key={`msg-${entry.item.id}`}
                      msg={entry.item}
                      streamingMsgId={streamingMsgId}
                      regeneratingId={regeneratingId}
                      copiedId={copiedId}
                      onCopy={handleCopy}
                      onRegenerate={(id) =>
                        activeConversationId && handleRegenerate(id, activeConversationId)
                      }
                    />
                  );
                });
              })()}
              {sending && !streamingMsgId && (
                <div className="flex justify-start animate-in fade-in duration-200">
                  <div className="shrink-0 mt-3 mr-2">
                    <span className="block h-2 w-2 rounded-full bg-cyan" />
                  </div>
                  <div className="bg-surface-mid rounded-lg px-5 py-4 flex items-center gap-1.5">
                    <span
                      className="block h-2 w-2 rounded-full bg-on-surface-variant/60 animate-bounce"
                      style={{ animationDelay: "0ms" }}
                    />
                    <span
                      className="block h-2 w-2 rounded-full bg-on-surface-variant/60 animate-bounce"
                      style={{ animationDelay: "150ms" }}
                    />
                    <span
                      className="block h-2 w-2 rounded-full bg-on-surface-variant/60 animate-bounce"
                      style={{ animationDelay: "300ms" }}
                    />
                  </div>
                </div>
              )}
              <div ref={messagesEndRef} />
            </div>
          )}
        </div>

        {/* Floating Composer */}
        <div
          className="absolute bottom-6 left-0 flex justify-center px-6 pointer-events-none"
          style={{ right: "0" }}
        >
          <div className="w-full max-w-3xl pointer-events-auto">
            {readOnly ? (
              <div className="chat-composer rounded-xl border border-violet bg-surface-lowest/80 backdrop-blur-2xl shadow-[var(--shadow-float)] p-3 text-center">
                <p className="text-xs text-on-surface-variant font-mono">
                  Read-only — replies arrive via Telegram
                </p>
              </div>
            ) : (
              <div className="chat-composer rounded-xl border border-violet bg-surface-lowest/80 backdrop-blur-2xl shadow-[var(--shadow-float)] ring-1 ring-violet/20 focus-within:ring-violet/40 transition-all p-3">
                {/* Provider/model selector row */}
                {providers.length > 0 && (
                  <div className="mb-2 flex items-center gap-2 overflow-hidden">
                    <span className="text-xs text-on-surface-variant shrink-0">Model:</span>
                    <div className="flex-1 min-w-0 overflow-hidden relative">
                      <div
                        className="flex flex-nowrap gap-1.5 overflow-x-auto pb-6 -mb-6 hide-scrollbar"
                        style={{
                          maskImage:
                            "linear-gradient(to left, transparent 0%, black 60px, black 100%)",
                          WebkitMaskImage:
                            "linear-gradient(to left, transparent 0%, black 60px, black 100%)",
                          paddingRight: "60px",
                        }}
                      >
                        {providers.map((p) => (
                          <button
                            key={p.name}
                            onClick={() => setSelectedProvider(p.name)}
                            className={`shrink-0 whitespace-nowrap px-2.5 py-0.5 rounded-full text-xs font-mono transition-all duration-100 border cursor-pointer ${
                              selectedProvider === p.name
                                ? "border-violet/60 bg-violet/20 text-violet-light"
                                : "border-violet/20 bg-violet/10 text-on-surface-variant hover:border-violet/40 hover:bg-violet/20 hover:text-violet-light"
                            }`}
                          >
                            {p.model || p.name}
                          </button>
                        ))}
                      </div>
                    </div>
                  </div>
                )}
                {attachedFiles.length > 0 && (
                  <div className="mb-2 flex flex-wrap gap-2">
                    {attachedFiles.map((att, fi) => (
                      <div
                        key={`${att.file.name}-${fi}`}
                        className="flex items-center gap-2 rounded-md bg-surface-mid px-2 py-1 text-xs text-on-surface"
                      >
                        {att.file.type.startsWith("image/") ? (
                          <img
                            src={att.dataUrl}
                            alt={att.file.name}
                            className="h-8 w-8 rounded object-cover"
                          />
                        ) : (
                          <FileIcon
                            className="h-4 w-4 shrink-0 text-on-surface-variant"
                            aria-hidden="true"
                          />
                        )}
                        <span className="truncate max-w-[120px]">{att.file.name}</span>
                        <button
                          onClick={() => removeAttachment(fi)}
                          className="text-on-surface-variant hover:text-error"
                          aria-label={`Remove ${att.file.name}`}
                        >
                          &times;
                        </button>
                      </div>
                    ))}
                  </div>
                )}

                <div className="flex items-end gap-2 w-full">
                  <button
                    onClick={() => fileInputRef.current?.click()}
                    className="mb-0.5 shrink-0 inline-flex h-9 w-9 items-center justify-center rounded-md text-on-surface-variant hover:text-violet hover:bg-violet/15 transition-colors cursor-pointer"
                    aria-label="Attach files"
                    title="Attach files"
                  >
                    <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                      <path
                        d="M6 8.5l3.8-3.8a2 2 0 112.8 2.8L7.8 12.3a3.5 3.5 0 11-5-5L7.2 2.9"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                      />
                    </svg>
                  </button>
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    className="hidden"
                    onChange={handleFilesPicked}
                  />

                  {/* Mic button */}
                  <button
                    onClick={handleMic}
                    disabled={transcribing}
                    className={`mb-0.5 shrink-0 inline-flex h-9 w-9 items-center justify-center rounded-md transition-colors ${
                      recording
                        ? "text-error bg-error/10 hover:bg-error/20 animate-pulse cursor-pointer"
                        : transcribing
                          ? "text-on-surface-variant opacity-50 cursor-wait"
                          : "text-on-surface-variant hover:text-violet hover:bg-violet/15 cursor-pointer"
                    }`}
                    aria-label={recording ? "Stop recording" : "Record voice message"}
                    title={recording ? "Stop recording" : "Voice input"}
                  >
                    {transcribing ? (
                      <svg
                        width="18"
                        height="18"
                        viewBox="0 0 16 16"
                        fill="none"
                        className="animate-spin"
                      >
                        <circle
                          cx="8"
                          cy="8"
                          r="6"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeDasharray="20 14"
                        />
                      </svg>
                    ) : (
                      <svg width="18" height="18" viewBox="0 0 16 16" fill="none">
                        <rect
                          x="5"
                          y="1"
                          width="6"
                          height="9"
                          rx="3"
                          stroke="currentColor"
                          strokeWidth="1.5"
                        />
                        <path
                          d="M2.5 8a5.5 5.5 0 0011 0"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                        <line
                          x1="8"
                          y1="13.5"
                          x2="8"
                          y2="15"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeLinecap="round"
                        />
                      </svg>
                    )}
                  </button>

                  <textarea
                    ref={composeRef}
                    rows={1}
                    placeholder={
                      activeConversationId ? "Message openCrow..." : "Start a new conversation..."
                    }
                    value={composing}
                    onChange={(e) => {
                      setComposing(e.target.value);
                      e.target.style.height = "auto";
                      e.target.style.height = Math.min(e.target.scrollHeight, 72) + "px";
                    }}
                    onKeyDown={handleKeyDown}
                    className="flex-1 min-w-0 bg-transparent text-on-surface placeholder:text-on-surface-variant px-3 py-2 rounded text-sm font-body focus:outline-none focus-visible:outline-none resize-none overflow-y-auto leading-5"
                    style={{ height: "36px", maxHeight: "72px", outline: "none" }}
                  />

                  <button
                    onClick={handleSend}
                    disabled={!composing.trim() || sending}
                    className="mb-0.5 shrink-0 inline-flex h-9 w-9 items-center justify-center rounded-md border border-violet/40 bg-violet/10 text-violet hover:bg-violet/20 hover:border-violet hover:text-violet-light transition-colors disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer"
                    aria-label="Send message"
                    title="Send message"
                  >
                    {sending ? (
                      <svg
                        width="18"
                        height="18"
                        viewBox="0 0 16 16"
                        fill="none"
                        className="animate-spin"
                      >
                        <circle
                          cx="8"
                          cy="8"
                          r="6"
                          stroke="currentColor"
                          strokeWidth="1.5"
                          strokeDasharray="20 14"
                        />
                      </svg>
                    ) : (
                      <svg
                        width="18"
                        height="18"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="1.5"
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        style={{ marginLeft: "-1px", marginTop: "1px" }}
                      >
                        <path d="M10 14l11 -11" />
                        <path d="M21 3l-6.5 18a0.55 .55 0 0 1 -1 0l-3.5 -7l-7 -3.5a0.55 .55 0 0 1 0 -1l18 -6.5" />
                      </svg>
                    )}
                  </button>
                </div>
                {lastUsage && (
                  <div className="flex justify-end px-1 pt-0.5">
                    <span className="text-xs text-on-surface-variant font-mono opacity-60">
                      ^{lastUsage.promptTokens} v{lastUsage.completionTokens} Σ
                      {lastUsage.totalTokens}
                    </span>
                  </div>
                )}
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
